Feature/auth
Premium-Academy-Pro/Premium-Academy pull request #8
Opened 2024-06-05 16:57 UTC by MaicolAA

Draf pull request for review changes

2024-06-06 05:53 UTC, MachinEmmus commented on src/app/(auth)/components/styles.css
> +:root {
Hice unos ajustes en mi rama para que el responsive funcione un poco mejor ademas, me gustaria ver si sacamos los style.css de la carpeta components y la llevamos a una mas descriptiva well done!

2024-06-06 05:56 UTC, MachinEmmus commented on src/app/(auth)/components/Icon.js
> +  return (
Agregemos un fragmento solo por consistencia <> </>

2024-06-06 05:59 UTC, MachinEmmus requested changes
Comentarios iniciales

2024-06-06 05:59 UTC, MachinEmmus commented on src/app/(auth)/components/NumCode.js
> +  return (
Remplazemos el div por un fragmento (<></>) recordemos que entre sus beneficios no anade elementos al DOM y es mejor para el rendimiento de la aplicacion

2024-06-06 05:59 UTC, MachinEmmus commented on src/app/(dashboard)/home/page.js
> +import CoursesView from "./views/courses";
comillas simples

2024-06-06 06:14 UTC, MachinEmmus commented on src/app/(auth)/components/AuthForm.js
> +import React, { useState } from 'react';
No es necesario importar React

2024-06-06 06:14 UTC, MachinEmmus commented on src/app/(auth)/components/Icons.js
> +import React from 'react';
No es necesario

2024-06-07 01:54 UTC, MaicolAA commented on src/app/(auth)/components/Icon.js
> +  return (
OK

2024-06-07 01:55 UTC, MaicolAA commented on src/app/(dashboard)/home/page.js
> +import CoursesView from "./views/courses";
ok

2024-06-07 01:57 UTC, MaicolAA commented on src/app/(auth)/components/AuthForm.js
> +import React, { useState } from 'react';
ok

2024-06-07 01:59 UTC, MaicolAA commented on src/app/(auth)/components/Icons.js
> +import React from 'react';
ok

2024-06-07 01:59 UTC, MaicolAA commented on src/app/(auth)/components/NumCode.js
> +  return (
ok

2024-06-07 02:06 UTC, closed without merging